let list = [
    {
        "supplierName": "新郑市悦大化妆品商行",
        "supplierId": 2272,
        "purchaseAdviceList": [
            {
                "purchaseAdviceCount": 1,
                "supplierSkuList": [
                    {
                        "gmtModified": "1616665204000",
                        "supplierId": "2639",
                        "p_referencePrice": "10.26",
                        "modifier": "lazbaohz",
                        "goodSkuIdList": null,
                        "skuIds": null,
                        "type": null,
                        "aliId": "2206824136829",
                        "p_amountOnsale": "351220.0",
                        "isDeleted": "n",
                        "p_categoryName": "唇釉",
                        "price": null,
                        "p_sourceUrl": "http://detail.1688.com/offer/627650782572.html",
                        "p_productName": "TVLV小提琴柔雾丝绒网红迷你空气唇釉学生款平价批发快手抖音直播",
                        "id": "1204",
                        "skuId": "4621987450732",
                        "localGoodSkuId": "2984",
                        "specId": "2687f6eaa927b7b42a6849e240078ef4",
                        "supplierName": "悦大化妆品",
                        "p_status": "published",
                        "creator": "lazbaohz",
                        "productId": "627650782572",
                        "libSkuCode": null,
                        "libSkuCodeList": null,
                        "amountOnsale": "87747",
                        "gmtCreate": "1616665204000",
                        "userId": "10",
                        "isDefault": "1",
                        "openCode": null,
                        "productGoodsId": "4683"
                    }
                ],
                "safeStockCount": 0,
                "dailySales": 0,
                "purchasePlanCount": 0,
                "orderCount": 2,
                "goodsSkuId": 2984,
                "costAmount": 10.8,
                "type": "1",
                "outCountOf30day": 3,
                "appropriationWayCount": 0,
                "purchaseUrl": "https://detail.1688.com/offer/627650782572.html?spm=a26352.b28411319.offerlist.81.74d81e62VyjQDE",
                "purchaseAdviceCountNew": 1,
                "positionId": 400,
                "warehouseId": 800,
                "imageUrl": "https://th-live.slatic.net/p/4dadd37764ae9921d3b44b4b5aab8860.jpg",
                "purchaseWayCount": 0,
                "stockId": 3183,
                "positionNo": "默认良品仓",
                "goodsCode": "DCH114003",
                "averagePrice": 7.7,
                "goodsName": "DCH114-603＃草莓豆沙",
                "stockCount": 1
            }
        ]
    },
    {
        "supplierName": "湖州木子维财网络科技有限公司",
        "supplierId": 2241,
        "purchaseAdviceList": [
            {
                "purchaseAdviceCount": 2,
                "supplierSkuList": [
                    {
                        "gmtModified": "1617265800000",
                        "supplierId": "3016",
                        "p_referencePrice": "0.8~1.0",
                        "modifier": "yeaizhen",
                        "goodSkuIdList": null,
                        "skuIds": null,
                        "type": null,
                        "aliId": "2206824136829",
                        "p_amountOnsale": "12371.0",
                        "isDeleted": "n",
                        "p_categoryName": "女士香水",
                        "price": null,
                        "p_sourceUrl": "http://detail.1688.com/offer/578873333958.html",
                        "p_productName": "咪玥乐妮女士香水小样4ml试管香水持久淡香淡雅花果香10款学生",
                        "id": "2291",
                        "skuId": "4008834438746",
                        "localGoodSkuId": "2802",
                        "specId": "311ffeeb025f32cd485986168bc5dd92",
                        "supplierName": "咪玥乐妮美妆",
                        "p_status": "published",
                        "creator": "yeaizhen",
                        "productId": "578873333958",
                        "libSkuCode": null,
                        "libSkuCodeList": null,
                        "amountOnsale": "0",
                        "gmtCreate": "1617265800000",
                        "userId": "10",
                        "isDefault": "1",
                        "openCode": null,
                        "productGoodsId": "8511"
                    }
                ],
                "safeStockCount": 0,
                "dailySales": 0,
                "purchasePlanCount": 0,
                "orderCount": 2,
                "goodsSkuId": 2802,
                "costAmount": 1,
                "type": "1",
                "outCountOf30day": 0,
                "appropriationWayCount": 0,
                "purchaseUrl": "https://detail.1688.com/offer/578873333958.html?spm=a26352.13672862.offerlist.2223.79964e915VO5ON",
                "purchaseAdviceCountNew": 2,
                "positionId": 400,
                "warehouseId": 800,
                "imageUrl": "https://th-live.slatic.net/p/ac3a1fdaf185cc0ad6a42289fa47c951.jpg",
                "purchaseWayCount": 0,
                "stockId": 3001,
                "positionNo": "默认良品仓",
                "goodsCode": "DCH192009",
                "averagePrice": 0,
                "goodsName": "DCH192-1335回眸一笑-4ml",
                "stockCount": 0
            },
            {
                "purchaseAdviceCount": 2,
                "supplierSkuList": [
                    {
                        "gmtModified": "1617269550000",
                        "supplierId": "3016",
                        "p_referencePrice": "0.8~1.0",
                        "modifier": "yeaizhen",
                        "goodSkuIdList": null,
                        "skuIds": null,
                        "type": null,
                        "aliId": "2206824136829",
                        "p_amountOnsale": "12371.0",
                        "isDeleted": "n",
                        "p_categoryName": "女士香水",
                        "price": null,
                        "p_sourceUrl": "http://detail.1688.com/offer/578873333958.html",
                        "p_productName": "咪玥乐妮女士香水小样4ml试管香水持久淡香淡雅花果香10款学生",
                        "id": "2377",
                        "skuId": "4008834438742",
                        "localGoodSkuId": "2806",
                        "specId": "522b520f6b910f38a8ad92fe72c5c2b5",
                        "supplierName": "咪玥乐妮美妆",
                        "p_status": "published",
                        "creator": "yeaizhen",
                        "productId": "578873333958",
                        "libSkuCode": null,
                        "libSkuCodeList": null,
                        "amountOnsale": "0",
                        "gmtCreate": "1617269550000",
                        "userId": "10",
                        "isDefault": "1",
                        "openCode": null,
                        "productGoodsId": "9238"
                    }
                ],
                "safeStockCount": 0,
                "dailySales": 0,
                "purchasePlanCount": 0,
                "orderCount": 3,
                "goodsSkuId": 2806,
                "costAmount": 1,
                "type": "1",
                "outCountOf30day": 0,
                "appropriationWayCount": 0,
                "purchaseUrl": "https://detail.1688.com/offer/578873333958.html?spm=a26352.13672862.offerlist.2223.79964e915VO5ON",
                "purchaseAdviceCountNew": 2,
                "positionId": 400,
                "warehouseId": 800,
                "imageUrl": "https://th-live.slatic.net/p/ac3a1fdaf185cc0ad6a42289fa47c951.jpg",
                "purchaseWayCount": 0,
                "stockId": 3005,
                "positionNo": "默认良品仓",
                "goodsCode": "DCH192005",
                "averagePrice": 0,
                "goodsName": "DCH192-1331紫烟轻绕-4ml",
                "stockCount": 1
            }
        ]
    },
]